// Inline style tokens for the admin pages — the same dark palette and
// inline-style approach as /wallet (Session 05), so the console reads as part
// of the same app without introducing a styling dependency.
export const adminStyles = {
  main: {
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    minHeight: '100vh',
    padding: '2rem 1.5rem 4rem',
    background: 'linear-gradient(160deg, #0f172a 0%, #1e293b 100%)',
    color: '#f8fafc',
  },
  shell: { maxWidth: 1080, margin: '0 auto' },
  h1: { fontSize: '1.75rem', margin: '0 0 0.25rem' },
  h2: { margin: '0 0 0.75rem', fontSize: '1.1rem' },
  muted: { color: '#94a3b8' },
  card: {
    border: '1px solid #334155',
    borderRadius: 12,
    padding: '1.25rem',
    background: 'rgba(148, 163, 184, 0.08)',
    marginTop: '1.25rem',
  },
  row: { display: 'flex', flexWrap: 'wrap', gap: '0.75rem', alignItems: 'center' },
  button: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: '1px solid #38bdf8',
    background: '#0ea5e9',
    color: '#04263a',
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonDanger: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: '1px solid #f87171',
    background: '#ef4444',
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonGhost: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: '1px solid #475569',
    background: 'transparent',
    color: '#e2e8f0',
    cursor: 'pointer',
  },
  input: {
    padding: '0.5rem 0.65rem',
    borderRadius: 8,
    border: '1px solid #334155',
    background: '#0b1220',
    color: '#e2e8f0',
    fontSize: '0.9rem',
  },
  label: { display: 'block', marginBottom: '0.25rem', color: '#cbd5e1', fontSize: '0.85rem' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem' },
  th: {
    textAlign: 'left',
    padding: '0.5rem 0.4rem',
    borderBottom: '1px solid #334155',
    color: '#cbd5e1',
    fontWeight: 600,
  },
  td: { padding: '0.5rem 0.4rem', borderBottom: '1px solid #1e293b', verticalAlign: 'top' },
  badge: {
    display: 'inline-block',
    padding: '0.1rem 0.5rem',
    borderRadius: 9999,
    border: '1px solid #475569',
    fontSize: '0.75rem',
    color: '#e2e8f0',
  },
  status: { marginTop: '1rem', color: '#cbd5e1' },
  confirmPanel: {
    marginTop: '0.5rem',
    padding: '0.75rem',
    border: '1px solid #fbbf24',
    borderRadius: 8,
    background: 'rgba(251, 191, 36, 0.08)',
  },
  thumb: {
    width: 120,
    height: 120,
    objectFit: 'cover',
    borderRadius: 8,
    border: '1px solid #334155',
    background: '#0b1220',
  },
} as const;
