// =============================================================================
// Anti-leak tests (Session 09) — D1 forensic watermark + D2 video trace.
//
// Same posture as every suite before it: no real database, bucket or image
// library. The shared in-memory Prisma fake, a fake StorageClient and a fake
// ImageProcessor whose `watermark` echoes its label back into the bytes (so the
// "rendered" watermark text is inspectable), wired through `buildServer`; auth
// cookies come from the real register→verify→login flow.
//
// The properties under test, straight from the session's acceptance criteria:
//   * two viewers of the same content get different codes
//   * the same viewer twice in one minute gets the same code; a minute later,
//     a different one
//   * one AuditLog row per serve, and a code round-trips to the right viewer
//     through it — and only through it
//   * the watermark text carries no substring of the viewer's email or id
//   * video serves return the code as JSON, generated by the same helper, with
//     the same audit trail
//   * WATERMARK_TRACE_SECRET is validated at boot (present, ≥ 32 chars)
// =============================================================================
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { buildServer } from '../../index.js';
import type { PrismaClient } from '../../lib/prisma.js';
import type { StorageClient } from '../../lib/storage.js';
import type { ImageProcessor } from '../../lib/image.js';
import {
  createFakeEmailer,
  createFakePrisma,
  seedContent,
  seedGenerationJob,
  seedProfile,
  type FakePrisma,
} from '../../test/fake-prisma.js';
import {
  TRACE_CODE_LENGTH,
  WATERMARK_BRAND,
  computeTraceCode,
  createTraceRecorder,
  traceWatermarkLabel,
} from './trace.js';

const TRACE_RE = /^[A-Z2-7]{8}$/;
const LABEL_RE = new RegExp(`^${WATERMARK_BRAND} • ([A-Z2-7]{${TRACE_CODE_LENGTH}})$`);
const WATERMARK_MARKER = 'WATERMARKED:';

// ── Fakes ────────────────────────────────────────────────────────────────────
function createFakeStorage(): StorageClient {
  return {
    uploadFile: vi.fn(async (_b: string, key: string) => key),
    getSignedUrl: vi.fn(
      async (_b: string, key: string, ttl: number) => `https://signed.example/${key}?ttl=${ttl}`,
    ),
    getObject: vi.fn(async () => Buffer.from('RAW-IMAGE-BYTES')),
    deleteFile: vi.fn(async () => {}),
  };
}

/** Echoes the label into the output so the test can read the "rendered" mark. */
function createFakeImages(): ImageProcessor {
  return {
    getDimensions: vi.fn(async () => ({ width: 800, height: 600 })),
    watermark: vi.fn(async (_buffer: Buffer, label: string) =>
      Buffer.from(`${WATERMARK_MARKER}${label}`),
    ),
  };
}

interface Harness {
  app: Awaited<ReturnType<typeof buildServer>>;
  prisma: FakePrisma;
  images: ImageProcessor;
}

async function makeApp(): Promise<Harness> {
  const prisma = createFakePrisma();
  const images = createFakeImages();
  const app = await buildServer({
    prisma: prisma as unknown as PrismaClient,
    emailer: createFakeEmailer(),
    storage: createFakeStorage(),
    images,
  });
  return { app, prisma, images };
}

async function loginAs(
  h: Harness,
  role: 'model' | 'subscriber',
  email: string,
): Promise<{ cookie: string; userId: string; email: string }> {
  await h.app.inject({
    method: 'POST',
    url: '/api/auth/register',
    payload: { email, password: 'supersecret', displayName: `Test ${role}`, role },
  });
  const user = h.prisma.__users.find((u) => u.email === email)!;
  await h.app.inject({ method: 'GET', url: `/api/auth/verify-email?token=${user.verifyToken}` });
  const login = await h.app.inject({
    method: 'POST',
    url: '/api/auth/login',
    payload: { email, password: 'supersecret' },
  });
  return {
    cookie: login.cookies.find((c) => c.name === 'access_token')!.value,
    userId: user.id,
    email,
  };
}

function grantAccess(h: Harness, contentId: string, userId: string) {
  h.prisma.__accesses.push({
    id: `acc_seed_${h.prisma.__accesses.length + 1}`,
    contentId,
    userId,
    grantReason: 'subscription_standard',
    grantedAt: new Date(),
    expiresAt: null,
  });
}

const serve = (h: Harness, contentId: string, cookie: string) =>
  h.app.inject({
    method: 'GET',
    url: `/api/content/${contentId}/serve`,
    cookies: { access_token: cookie },
  });

/** The trace code rendered into a served image body. */
function codeIn(body: string): string {
  expect(body.startsWith(WATERMARK_MARKER)).toBe(true);
  const match = body.slice(WATERMARK_MARKER.length).match(LABEL_RE);
  expect(match, `watermark text "${body}" is not brand + trace code`).not.toBeNull();
  return match![1];
}

const serveRows = (h: Harness, action: string) =>
  h.prisma.__auditLogs.filter((row) => row.action === action);

type TraceMeta = { viewerId: string; traceCode: string; servedAt: string };

/** The forensic lookup itself: code → AuditLog row → viewer. */
function resolveCode(h: Harness, code: string) {
  return h.prisma.__auditLogs.filter((row) => (row.metadata as TraceMeta)?.traceCode === code);
}

// =============================================================================
describe('computeTraceCode (pure)', () => {
  const base = {
    secret: 'unit-test-secret-at-least-32-characters-long!!',
    entityId: 'content_1',
    viewerId: 'user_a',
    servedAt: new Date('2026-09-11T12:00:10.000Z'),
  };

  it('is 8 chars of RFC 4648 base32 and deterministic for identical inputs', () => {
    const a = computeTraceCode(base);
    expect(a).toMatch(TRACE_RE);
    expect(a).toHaveLength(TRACE_CODE_LENGTH);
    expect(computeTraceCode({ ...base })).toBe(a);
  });

  it('is stable within a minute and changes across the minute boundary', () => {
    const a = computeTraceCode(base);
    expect(computeTraceCode({ ...base, servedAt: new Date('2026-09-11T12:00:59.999Z') })).toBe(a);
    expect(computeTraceCode({ ...base, servedAt: new Date('2026-09-11T12:01:00.000Z') })).not.toBe(
      a,
    );
  });

  it('differs per viewer, per entity, and per secret', () => {
    const a = computeTraceCode(base);
    expect(computeTraceCode({ ...base, viewerId: 'user_b' })).not.toBe(a);
    expect(computeTraceCode({ ...base, entityId: 'content_2' })).not.toBe(a);
    expect(computeTraceCode({ ...base, secret: `${base.secret}x` })).not.toBe(a);
  });

  it('separates fields so concatenation cannot alias two different pairs', () => {
    // ("ab", "c") vs ("a", "bc") — same characters, different pairs.
    const x = computeTraceCode({ ...base, entityId: 'ab', viewerId: 'c' });
    const y = computeTraceCode({ ...base, entityId: 'a', viewerId: 'bc' });
    expect(x).not.toBe(y);
  });

  it('never contains the viewer id or entity id', () => {
    const code = computeTraceCode({ ...base, viewerId: 'ZZZZ', entityId: 'YYYY' });
    expect(code).not.toContain('ZZZZ');
    expect(code).not.toContain('YYYY');
    expect(traceWatermarkLabel(code)).toBe(`${WATERMARK_BRAND} • ${code}`);
  });
});

describe('createTraceRecorder', () => {
  it('writes one AuditLog row per issue, keyed by viewer, carrying the code', async () => {
    const prisma = createFakePrisma();
    const at = new Date('2026-09-11T12:00:10.000Z');
    const recorder = createTraceRecorder({
      prisma: prisma as unknown as PrismaClient,
      secret: 'unit-test-secret-at-least-32-characters-long!!',
      now: () => at,
    });

    const first = await recorder.issue({ entity: 'Content', entityId: 'c1', viewerId: 'u1' });
    const second = await recorder.issue({ entity: 'Content', entityId: 'c1', viewerId: 'u1' });
    expect(first.traceCode).toBe(second.traceCode);
    expect(first.servedAt).toEqual(at);

    // Two serves → two rows, even though the code repeats within the minute.
    expect(prisma.__auditLogs).toHaveLength(2);
    expect(prisma.__auditLogs[0]).toMatchObject({
      actorId: 'u1',
      action: 'content.served',
      entity: 'Content',
      entityId: 'c1',
      metadata: { viewerId: 'u1', traceCode: first.traceCode, servedAt: at.toISOString() },
    });

    const gen = await recorder.issue({ entity: 'GenerationJob', entityId: 'g1', viewerId: 'u1' });
    expect(prisma.__auditLogs[2]).toMatchObject({
      action: 'generation.image_served',
      entity: 'GenerationJob',
      entityId: 'g1',
      metadata: { traceCode: gen.traceCode },
    });
  });
});

// =============================================================================
describe('D1 — GET /api/content/:contentId/serve (image)', () => {
  let h: Harness;
  let modelId: string;

  beforeEach(async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date('2026-09-11T12:00:10.000Z'));
    h = await makeApp();
    const model = await loginAs(h, 'model', 'model@example.com');
    modelId = model.userId;
    seedProfile(h.prisma, modelId);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('two subscribers viewing the same content get different codes; each is audited and round-trips', async () => {
    const alice = await loginAs(h, 'subscriber', 'alice@example.com');
    const bob = await loginAs(h, 'subscriber', 'bob@example.com');
    const c = seedContent(h.prisma, { modelId, tier: 'STANDARD' });
    grantAccess(h, c.id, alice.userId);
    grantAccess(h, c.id, bob.userId);

    const resA = await serve(h, c.id, alice.cookie);
    const resB = await serve(h, c.id, bob.cookie);
    expect(resA.statusCode).toBe(200);
    expect(resB.statusCode).toBe(200);
    expect(resA.headers['cache-control']).toBe('no-store');

    const codeA = codeIn(resA.rawPayload.toString());
    const codeB = codeIn(resB.rawPayload.toString());
    expect(codeA).not.toBe(codeB);

    // One row per serve, and the lookup lands on the right viewer.
    const rows = serveRows(h, 'content.served');
    expect(rows).toHaveLength(2);
    expect(rows.map((r) => r.entityId)).toEqual([c.id, c.id]);

    const foundA = resolveCode(h, codeA);
    expect(foundA).toHaveLength(1);
    expect(foundA[0].actorId).toBe(alice.userId);
    expect((foundA[0].metadata as TraceMeta).viewerId).toBe(alice.userId);

    const foundB = resolveCode(h, codeB);
    expect(foundB).toHaveLength(1);
    expect((foundB[0].metadata as TraceMeta).viewerId).toBe(bob.userId);
  });

  it('the same subscriber twice within a minute gets the same code, and a new one next minute', async () => {
    const alice = await loginAs(h, 'subscriber', 'alice@example.com');
    const c = seedContent(h.prisma, { modelId, tier: 'FREE' });

    const first = codeIn((await serve(h, c.id, alice.cookie)).rawPayload.toString());
    vi.setSystemTime(new Date('2026-09-11T12:00:45.000Z'));
    const second = codeIn((await serve(h, c.id, alice.cookie)).rawPayload.toString());
    expect(second).toBe(first);

    vi.setSystemTime(new Date('2026-09-11T12:01:05.000Z'));
    const third = codeIn((await serve(h, c.id, alice.cookie)).rawPayload.toString());
    expect(third).not.toBe(first);

    // Still one audit row per serve — the code de-duplicates marks, not rows.
    expect(serveRows(h, 'content.served')).toHaveLength(3);
    expect(resolveCode(h, first)).toHaveLength(2);
    expect(resolveCode(h, third)).toHaveLength(1);
  });

  it('non-leakage: the watermark text contains no substring of the viewer email or raw id', async () => {
    const alice = await loginAs(h, 'subscriber', 'alice.leaktest@example.com');
    const c = seedContent(h.prisma, { modelId, tier: 'FREE' });

    const body = (await serve(h, c.id, alice.cookie)).rawPayload.toString();
    const label = body.slice(WATERMARK_MARKER.length);
    expect(label).toMatch(LABEL_RE);

    // Every ≥4-char window of the email and of the id, case-insensitively —
    // the id alphabet overlaps base32's, so a lax check could miss a leak.
    // Windows that are themselves part of the brand word are not evidence.
    const rendered = label.toUpperCase();
    const brand = WATERMARK_BRAND.toUpperCase();
    for (const secret of [alice.email, alice.userId]) {
      const upper = secret.toUpperCase();
      for (let len = 4; len <= upper.length; len++) {
        for (let i = 0; i + len <= upper.length; i++) {
          const window = upper.slice(i, i + len);
          if (brand.includes(window)) continue;
          expect(rendered, `leaked "${window}"`).not.toContain(window);
        }
      }
    }
    // The pure form of the same property: the code is opaque without the key.
    expect(label).not.toContain(alice.userId);
    expect(label).not.toContain('alice');
    expect(label).not.toContain('example');
    // And the fake watermark received exactly that label — nothing else went to the renderer.
    expect(h.images.watermark).toHaveBeenCalledWith(
      expect.any(Buffer),
      traceWatermarkLabel(codeIn(body)),
      'image/jpeg',
    );
  });

  it('issues no trace and writes no audit row when access is denied', async () => {
    const alice = await loginAs(h, 'subscriber', 'alice@example.com');
    const c = seedContent(h.prisma, { modelId, tier: 'STANDARD' });

    const res = await serve(h, c.id, alice.cookie);
    expect(res.statusCode).toBe(403);
    expect(serveRows(h, 'content.served')).toHaveLength(0);
    expect(h.images.watermark).not.toHaveBeenCalled();
  });
});

// =============================================================================
describe('D2 — GET /api/content/:contentId/serve (video, Option B)', () => {
  let h: Harness;
  let modelId: string;

  beforeEach(async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date('2026-09-11T12:00:10.000Z'));
    h = await makeApp();
    const model = await loginAs(h, 'model', 'model@example.com');
    modelId = model.userId;
    seedProfile(h.prisma, modelId);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('returns the signed URL plus a traceCode from the same helper, and audits the serve', async () => {
    const alice = await loginAs(h, 'subscriber', 'alice@example.com');
    const bob = await loginAs(h, 'subscriber', 'bob@example.com');
    const v = seedContent(h.prisma, {
      modelId,
      tier: 'FREE',
      type: 'VIDEO',
      mimeType: 'video/mp4',
      storageKey: `content/${modelId}/clip.mp4`,
    });

    const resA = await serve(h, v.id, alice.cookie);
    expect(resA.statusCode).toBe(200);
    const bodyA = resA.json<{ signedUrl: string; expiresIn: number; traceCode: string }>();
    expect(bodyA.expiresIn).toBe(60);
    expect(bodyA.signedUrl).toContain('ttl=60');
    expect(bodyA.traceCode).toMatch(TRACE_RE);
    // No key in the JSON body other than inside the signed URL the client must fetch.
    expect(Object.keys(bodyA).sort()).toEqual(['expiresIn', 'signedUrl', 'traceCode']);

    // Same helper as D1: the code is exactly what computeTraceCode yields for
    // (content, viewer, this minute) under the test secret.
    expect(bodyA.traceCode).toBe(
      computeTraceCode({
        secret: process.env.WATERMARK_TRACE_SECRET!,
        entityId: v.id,
        viewerId: alice.userId,
        servedAt: new Date(),
      }),
    );

    const bodyB = (await serve(h, v.id, bob.cookie)).json<{ traceCode: string }>();
    expect(bodyB.traceCode).not.toBe(bodyA.traceCode);

    // Same audit trail as images: one row per serve, resolvable to the viewer.
    const rows = serveRows(h, 'content.served');
    expect(rows).toHaveLength(2);
    expect((resolveCode(h, bodyA.traceCode)[0].metadata as TraceMeta).viewerId).toBe(alice.userId);
    expect((resolveCode(h, bodyB.traceCode)[0].metadata as TraceMeta).viewerId).toBe(bob.userId);
    // No watermarking happens server-side for video — Option B by design.
    expect(h.images.watermark).not.toHaveBeenCalled();
  });
});

// =============================================================================
describe('D1 — GET /api/generations/:id/image', () => {
  it('watermarks with brand + trace code (never the email), audits, and the code round-trips', async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date('2026-09-11T12:00:10.000Z'));
    try {
      const h = await makeApp();
      const model = await loginAs(h, 'model', 'model@example.com');
      seedProfile(h.prisma, model.userId, undefined, { aiConsent: true });
      const sub = await loginAs(h, 'subscriber', 'sub.gen@example.com');
      const job = seedGenerationJob(h.prisma, { subscriberId: sub.userId, modelId: model.userId });

      const res = await h.app.inject({
        method: 'GET',
        url: `/api/generations/${job.id}/image`,
        cookies: { access_token: sub.cookie },
      });
      expect(res.statusCode).toBe(200);
      const body = res.rawPayload.toString();
      const code = codeIn(body);
      expect(body).not.toContain('sub.gen');
      expect(body).not.toContain(sub.userId);

      expect(code).toBe(
        computeTraceCode({
          secret: process.env.WATERMARK_TRACE_SECRET!,
          entityId: job.id,
          viewerId: sub.userId,
          servedAt: new Date(),
        }),
      );
      const rows = serveRows(h, 'generation.image_served');
      expect(rows).toHaveLength(1);
      expect(rows[0]).toMatchObject({
        actorId: sub.userId,
        entity: 'GenerationJob',
        entityId: job.id,
        metadata: { viewerId: sub.userId, traceCode: code },
      });
      // The stored object is untouched — the mark is applied at serve time only.
      expect(body).not.toContain(job.storageKey!);
    } finally {
      vi.useRealTimers();
    }
  });
});

// =============================================================================
describe('env.ts — WATERMARK_TRACE_SECRET', () => {
  const original = process.env.WATERMARK_TRACE_SECRET;

  afterEach(() => {
    process.env.WATERMARK_TRACE_SECRET = original;
    vi.resetModules();
  });

  it('crashes at boot when missing', async () => {
    delete process.env.WATERMARK_TRACE_SECRET;
    vi.resetModules();
    await expect(import('../../lib/env.js')).rejects.toThrow(/WATERMARK_TRACE_SECRET/);
  });

  it('crashes at boot when shorter than 32 chars', async () => {
    process.env.WATERMARK_TRACE_SECRET = 'too-short';
    vi.resetModules();
    await expect(import('../../lib/env.js')).rejects.toThrow(/at least 32 characters/);
  });

  it('boots with a 32+ char secret', async () => {
    process.env.WATERMARK_TRACE_SECRET = 'x'.repeat(32);
    vi.resetModules();
    await expect(import('../../lib/env.js')).resolves.toBeDefined();
  });
});
